home:
  path:
    - /
    - /page/{page:\d+}
  view: @blocks/pages/home.twig
  layers: @layers/tracking.yml
  trailing_slash: force

posts:
  type: post
  args:
    site_ids: [979, 1032]
  view: @blocks/pages/article.twig
  layers: @layers/tracking.yml
  trailing_slash: force

searches:
  path: /search/
  view: @blocks/pages/search.twig
  layers: @layers/tracking.yml
  trailing_slash: force

tags:
  path:
    - /tag/{tag}
    - /tag/{tag}/page/{page:\d+}
  view: @blocks/pages/tag.twig
  layers: @layers/tracking.yml
  trailing_slash: force

videos:
  path:
    - /video
    - /video/page/{page:\d+}
  view: @blocks/pages/video.twig
  layers: @layers/tracking.yml
  trailing_slash: force

quests:
  path:
    - /quest
    - /quest/page/{page:\d+}
  view: @blocks/pages/quest.twig
  layers: @layers/tracking.yml
  trailing_slash: force

contributors:
  path:
    - /contributor/{slug}
    - /contributor/{slug}/page/{page:\d+}
  view: @blocks/pages/contributor.twig
  layers: @layers/tracking.yml
  trailing_slash: force

nascar:
  path:
    - /motorsports
    - /motorsports/page/{page:\d+}
  view: @blocks/pages/nascar.twig
  layers: @layers/tracking.yml
  trailing_slash: force

mlb:
  path:
    - /mlb
    - /mlb/page/{page:\d+}
  view: @blocks/pages/mlb.twig
  layers: @layers/tracking.yml
  trailing_slash: force

parks:
  path:
    - /national-parks
    - /national-parks/page/{page:\d+}
  view: @blocks/pages/parks.twig
  layers: @layers/tracking.yml
  trailing_slash: force

pokemon:
  path:
    - /pokego/
    - /pokego/page/{page:\d+}
  view: @blocks/pages/pokemon.twig
  layers: @layers/tracking.yml
  trailing_slash: force

trexit:
  path:
    - /trexit/
    - /trexit/page/{page:\d+}
  view: @blocks/pages/trexit.twig

sl_index:
  path: /soundslocal/
  view: @blocks/pages/soundslocal_index.twig
  layers: @layers/tracking.yml
  trailing_slash: force

sl_episode:
  path: /soundslocal/episode/{slug}
  view: @blocks/pages/soundslocal_episode.twig
  layers: @layers/tracking.yml
  trailing_slash: force

ad:
  path: /_uac/adpage.html
  view: @blocks/pages/adpage.twig

notfound:
  path: /notfound.html
  view: @blocks/notfound.twig

rss_feed:
  path: /rss.xml
  view: @blocks/feeds/classic-feed.twig

denver_feed:
  path: /tag/denver/rss.xml
  view: @blocks/feeds/denver-feed.twig

appboy_manifest:
  path: /manifest.json
  view: @blocks/pages/appboy_manifest.twig

appboy_service_worker:
  path: /service-worker.js
  view: @blocks/pages/appboy_service_worker.twig

cats:
  path:
    - /catquest
    - /catquest/page/{page:\d+}
  view: @blocks/pages/catquest.twig
  layers: @layers/tracking.yml
  trailing_slash: force

local_news:
  path:
    - /local-news
    - /local-news/page/{page:\d+}
  view: @blocks/pages/local-news.twig
  layers: @layers/tracking.yml
  trailing_slash: force

didclintonwin:
  path: /didclintonwin
  view: @blocks/pages/didclintonwin.twig
  layers: @layers/tracking.yml
  trailing_slash: force

didthedonaldwin:
  path: /didthedonaldwin
  view: @blocks/pages/didthedonaldwin.twig
  layers: @layers/tracking.yml
  trailing_slash: force

